WebPKthucung/Controllers/ThongKeController.cs
using Microsoft.Ajax.Utilities;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Xml.Linq;
using WebPKthucung.App_Start;
using WebPKthucung.Models;


namespace WebPKthucung.Controllers
{
    public class ThongKeController : Controller
    {
        QLPKTHUCUNGEntities1 db = new QLPKTHUCUNGEntities1();
        // GET: ThongKe
        [HttpGet]
        public ActionResult Index()
        {
            var thongKe = new List<BaoCao>();
            int pageSize = 20;
            var list = thongKe.OrderBy(x => x.NgayBan);
            ViewBag.tongTienTheoThangNam = new List<BaoCaoThang>();
            ViewBag.TongDoanhThu = 0;
            return View(list.ToPagedList(1, pageSize));
        }
        [HttpPost]
        public ActionResult Index(int? page, int thangbatdau, int thangketthuc, int nambatdau, int namketthuc)
        {
            
            if (Session["Taikhoanadmin"] == null)
            {
                return RedirectToAction("dangnhap", "Admin");
            } else
            {
                ViewBag.thangbatdau = thangbatdau;
                ViewBag.thangketthuc = thangketthuc;
                ViewBag.nambatdau = nambatdau;
                ViewBag.namketthuc = namketthuc;
                DateTime batDau = new DateTime(nambatdau, thangbatdau, 1);
                DateTime ketThuc = new DateTime(namketthuc, thangketthuc, 30);
                var thongKe = (from a in db.DONDATHANGs where  a.NGAYDAT >= batDau &&  a.NGAYDAT <=ketThuc
                               join b in db.CTDONDATHANGs on a.MADH equals b.MADH
                               join c in db.SANPHAMs on b.MASP equals c.MASP
                               select new BaoCao
                               {
                                   MADH = a.MADH,
                                   maSanPham = b.MASP,
                                   TenSanPham = c.TENSP,
                                   SoLuongBan = b.SOLUONG,
                                   DonGiaBan = b.DONGIA,
                                   thanhTien = b.THANHTIEN,
                                   NgayBan = a.NGAYDAT,
                               }).OrderBy(x => x.NgayBan).ToList();
                var tongTienTheoThangNam = db.DONDATHANGs
                                            .Where(d =>  d.NGAYDAT >= batDau && d.NGAYDAT <= ketThuc)
                                            .GroupBy(d => new { d.NGAYDAT.Year, d.NGAYDAT.Month })
                                            .Select(g => new { Thang = g.Key.Month, Nam = g.Key.Year, TongTien = g.Sum(d => d.TONGTIEN) })
                                            .OrderBy(g => g.Nam)
                                            .ThenBy(g => g.Thang)
                                            .ToList();
                ViewBag.tongTienTheoThangNam = tongTienTheoThangNam.Select(d => new BaoCaoThang
                {
                    ThangBan = new DateTime(d.Nam, d.Thang, 1),
                    TongTien = d.TongTien
                }).ToList();
                ViewBag.TongDoanhThu = tongTienTheoThangNam.Sum(item => item.TongTien);
                ViewBag.baoCao = thongKe;
                int pageSize = 20;
                var pageNumber = page ?? 1;
                var list = thongKe.OrderBy(x => x.NgayBan);
                if (list.Count() == 0) ViewBag.TB = "Không có sản phẩm nào được bán trong thời gian này";
                return View(list.ToPagedList(pageNumber, pageSize));
            }
        }
        public ActionResult InBaoCao(int thangbatdau, int thangketthuc, int nambatdau, int namketthuc)
        {
            ViewBag.thangbatdau = thangbatdau;
            ViewBag.thangketthuc = thangketthuc;
            ViewBag.nambatdau = nambatdau;
            ViewBag.namketthuc = namketthuc;
            DateTime batDau = new DateTime(nambatdau, thangbatdau, 1);
            DateTime ketThuc = new DateTime(namketthuc, thangketthuc, 30);
            var thongKe = (from a in db.DONDATHANGs
                           where  a.NGAYDAT >= batDau && a.NGAYDAT <= ketThuc
                           join b in db.CTDONDATHANGs on a.MADH equals b.MADH
                           join c in db.SANPHAMs on b.MASP equals c.MASP
                           select new BaoCao
                           {
                               MADH = a.MADH,
                               maSanPham = b.MASP,
                               TenSanPham = c.TENSP,
                               SoLuongBan = b.SOLUONG,
                               DonGiaBan = b.DONGIA,
                               thanhTien = b.THANHTIEN,
                               NgayBan = a.NGAYDAT,
                           }).OrderBy(x => x.NgayBan).ToList();
            var tongTienTheoThangNam = db.DONDATHANGs
                                        .Where(d =>  d.NGAYDAT >= batDau && d.NGAYDAT <= ketThuc)
                                        .GroupBy(d => new { d.NGAYDAT.Year, d.NGAYDAT.Month })
                                        .Select(g => new { Thang = g.Key.Month, Nam = g.Key.Year, TongTien = g.Sum(d => d.TONGTIEN) })
                                        .OrderBy(g => g.Nam)
                                        .ThenBy(g => g.Thang)
                                        .ToList();
            ViewBag.tongTienTheoThangNam = tongTienTheoThangNam.Select(d => new BaoCaoThang
            {
                ThangBan = new DateTime(d.Nam, d.Thang, 1),
                TongTien = d.TongTien
            }).ToList();
            ViewBag.TongDoanhThu = tongTienTheoThangNam.Sum(item => item.TongTien);
            ViewBag.baoCao = thongKe;
            var list = thongKe.OrderBy(x => x.NgayBan);
            return View(list);
        }
    }
}

WebPKthucung/Views/ThongKe/InBaoCao.cshtml
@{
    ViewBag.Title = "PrintList1";
    Layout = null;
    int i = 0;
    int y = 0; 
}
<div style="display: flex; justify-content: center">
    <div>
        <link href="~/Content/print.css" rel="stylesheet" />
        <title>Bản in</title>
        <table id='tb_main_title' style='border-collapse: collapse;' name='tb_main_title' width='700' class="table-print-title">
            <tr>
                <th align='left' class='bold main_title'>
                    CÔNG TY TNHH PADDYSHOP
                </th>
            </tr>
            <tr>
                <th align='center' class='bold main_title' style='height:35px'>
                    BÁO CÁO DOANH THU
                </th>
            </tr>
        </table>
        <br />
        <table id='tb_main_body' style='border-collapse: collapse;' name='tb_main_body' width='700' class="table-print" border="1">
            <tr>
                <th>
                    STT
                </th>
                <th>
                    Thời gian
                </th>
                <th>
                    Mã đơn hàng
                </th>
                <th>
                    Mã sản phẩm
                </th>
                <th align="center">
                    Tên sản phẩm
                </th>
                <th>
                    Số lượng bán
                </th>
                <th>
                    Đơn giá bán
                </th>
                <th>
                    Thành Tiền
                </th>
            </tr>
            @foreach (var item in ViewBag.Baocao)
            {
                <tr>
                    <td align="center">
                        @{i++;}
                        @i
                    </td>
                    <td>
                        @item.NgayBan
                    </td>
                    <td>
                        @item.MADH
                    </td>
                    <td>
                        @item.maSanPham
                    </td>
                    <td>
                        @item.TenSanPham
                    </td>
                    <td>
                        @item.SoLuongBan
                    </td>
                    <td>
                        @string.Format("{0:#,##0}", item.DonGiaBan) đ
                    </td>
                    <td>
                        @string.Format("{0:#,##0}", item.DonGiaBan) đ
                    </td>
                </tr>
            }
        </table>
        <table id='tb_main_body' style='border-collapse: collapse; margin-top:40px; max-width:200px' name='tb_main_body' width='700' class="table-print" border="1">
            <tr>
                <th>
                    STT
                </th>
                <th>
                    Thời gian
                </th>
                <th>
                    Doanh thu
                </th>

            </tr>
            @foreach (var item in ViewBag.tongTienTheoThangNam)
            {
                <tr style="height:40px">
                    <td>
                        @{y++;}
                        @y
                    </td>
                    <td>
                        @item.ThangBan.ToString("MM/yyyy")
                    </td>
                    <td>
                        @string.Format("{0:#,##0}", item.TongTien) đ
                    </td>

                </tr>
            }
        </table>
        <div style="display: flex; justify-content: end; font-size: 20px">
            <h6>Tổng doanh thu từ @ViewBag.thangbatdau/@ViewBag.nambatdau đến @ViewBag.thangketthuc/@ViewBag.namketthuc là: @string.Format("{0:#,##0}", @ViewBag.TongDoanhThu) đ</h6>
        </div>
        @{
            var ngayIn = " ngày " + DateTime.Now.Day.ToString() + " tháng " + DateTime.Now.Month.ToString() + " năm " + DateTime.Now.Year.ToString();
        }
        <table id='tb_footer' name='tb_footer' width='700' border="0" class="fixheader">
            <tr>
                <td align='left' width='30%'></td>
                <td align='center' width='30%'></td>
                <td align='center' class='sign italic'>
                    Khánh Hòa, @ngayIn
                </td>
            </tr>
            <tr>
                <td align='center' width='30%' class='bold'>Giám đốc</td>
                <td align='center' width='30%' class='bold'>Kế toán</td>
                <td align='center' class='bold'>Người lập danh sách </td>
            </tr>
        </table>

    </div>
</div>

WebPKthucung/Views/ThongKe/Index.cshtml
@using PagedList.Mvc;
@model PagedList.PagedList<WebPKthucung.Models.BaoCao>
@{
    ViewBag.Title = "Thống kê";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    int i = 0;
    int y = 0;
    ViewBag.Trang = "Báo cáo doanh thu";
}

<div class="search_admin">
    <h1 class="Title_Admin_create_form">Thống kế doanh thu</h1>
    <div class="search_admin_header">
        @using (Html.BeginForm("Index", "ThongKe", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "search_admin_form", onsubmit = "return validateForm()" }))
        {
            <table class="Table_Details_Admin" style="margin-left:330px; margin-bottom:20px">
                <tr style="display:flex; justify-content:center; align-items:center">
                    <td style="display:flex; justify-content: center; align-items:center;">
                        <label for="" class="name_form_field" style="margin-right:10px">Tháng Bắt đầu : </label>
                        <input type="number" class="textfile" name="thangbatdau" style="min-width:50px" min="1" max="12" value="@ViewBag.thangbatdau" maxlength="2" id="startMonth">
                    </td>
                    <td style="display:flex; justify-content: center; align-items:center;">
                        <label for="" class="name_form_field" style="margin-right:10px">Năm bát đầu: </label>
                        <input type="number" class="textfile" name="nambatdau" style="min-width:50px" value="@ViewBag.nambatdau" maxlength="4" id="startYear">
                    </td>
                </tr>
                <tr style="display:flex">
                    <td style="display:flex; justify-content: center; align-items:center;">
                        <label for="" class="name_form_field" style="margin-right:10px">Tháng két thúc: </label>
                        <input type="number" class="textfile" name="thangketthuc" style="min-width:50px" min="1" max="12" value="@ViewBag.thangketthuc" maxlength="2" id="endMonth">
                    </td>
                    <td style="display:flex; justify-content: center; align-items:center;">
                        <label for="" class="name_form_field" style="margin-right:10px">Năm kết thúc: </label>
                        <input type="number" class="textfile" name="namketthuc" style="min-width:50px" value="@ViewBag.namketthuc" maxlength="4" id="endYear">
                    </td>
                </tr>
                
            </table>
            <h6 id="error" style="font-size: 16px; color: red"></h6>
            <div class="search_button" style="">
                <input type="submit" value="Báo cáo " class="search_button_btn" />
                <a href="@Url.Action("Index","ThongKe")"><input type="button" value="Nhập lại" class="search_button_btn" /></a>
                <a href="@Url.Action("InBaoCao", "ThongKe", new { @thangbatdau = ViewBag.thangbatdau, @thangketthuc = ViewBag.thangketthuc, @nambatdau = ViewBag.nambatdau, @namketthuc=ViewBag.namketthuc})" style="position: absolute; right:-400px;"><input type="button" value="In báo cáo" class="search_button_btn" /></a>
            </div>
        }
    </div>
    @if (ViewBag.TB == null)
    {
        <table class="table_dsadmin">
            <thead>
                <tr>
                    <th style="width: 30px;">STT</th>
                    <th style="width: 65px;">Thời gian</th>
                    <th style="width: 65px;">Mã đơn hàng</th>
                    <th style="width: 80px;">Mã sản phẩm</th>
                    <th style="width: 150px;">Tên sản phẩm</th>
                    <th style="width: 65px;">Số lượng bán</th>
                    <th style="width: 75px;">Đơn giá bán</th>
                    <th style="width: 80px;">Thành Tiền</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr style="height:40px">
                        <td>
                            @{i++;}
                            @i
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NgayBan)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MADH)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.maSanPham)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenSanPham)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SoLuongBan)
                        </td>
                        <td>
                            @string.Format("{0:#,##0}", item.DonGiaBan) đ
                        </td>
                        <td>
                            @string.Format("{0:#,##0}", item.DonGiaBan) đ
                        </td>
                    </tr>
                }
            </tbody>

        </table>
        <div style="display:block; justify-content:center; width: 100%">
            <div>
                <h6 style="font-size: 16px; display: flex; justify-content: center; margin:70px">Thống kê theo tháng</h6>
                <div style="display: flex; justify-content: center">
                    <table class="table_dsadmin" style="max-width: 500px">
                        <thead>
                            <tr>
                                <th style="width: 30px;">STT</th>
                                <th style="width: 65px;">Thời gian</th>
                                <th style="width: 75px;">Tổng doanh thu</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in ViewBag.tongTienTheoThangNam)
                            {
                                <tr style="height:40px">
                                    <td>
                                        @{y++;}
                                        @y
                                    </td>
                                    <td>
                                        @item.ThangBan.ToString("MM/yyyy")
                                    </td>
                                    <td>
                                        @string.Format("{0:#,##0}", item.TongTien) đ
                                    </td>

                                </tr>
                            }
                        </tbody>

                    </table>

                </div>
                <h6 style="font-size: 20px; display: flex; justify-content: center; margin:70px">Tổng toàn bộ doanh thu: @string.Format("{0:#,##0}", ViewBag.TongDoanhThu) VND</h6>
            </div>
        </div>

       
    }
    else
    {
        <h1 class="message_not_found">@ViewBag.TB</h1>
    }

</div>
<script>
    function validateForm() {
        var startMonth = document.getElementById("startMonth").value;
        var startYear = document.getElementById("startYear").value;
        var endMonth = document.getElementById("endMonth").value;
        var endYear = document.getElementById("endYear").value;

        // Kiểm tra tính hợp lệ của các giá trị
        if (startYear > endYear || (startYear === endYear && startMonth > endMonth)) {
            document.getElementById("error").innerHTML = "Thời gian bắt đầu phải nhỏ hơn thời gian kết thúc!";
            return false;
        }

        return true;
    }
</script>