WebPKthucung/Models/KICHTHUOC.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPKthucung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KICHTHUOC
    {
        public int MAKICHTHUOC { get; set; }
        public string MASP { get; set; }
        public int TENKICHTHUOC { get; set; }
        public Nullable<bool> ANHIEN { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}

WebPKthucung/Controllers/KichThuocController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using WebPKthucung.App_Start;
using WebPKthucung.Models;

namespace WebPKthucung.Controllers
{
    [AdminPhanQuyen(MACHUCNANG = "QL_KICHTHUOC")]
    public class KichThuocController : Controller
    {
        // GET: KichThuoc
        QLPKTHUCUNGEntities1 db = new QLPKTHUCUNGEntities1();
        public ActionResult Index(int? page)
        {
            if (page == null) page = 1;
            int pageSize = 7;
            var pageNumber = page ?? 1;
            var loais = from LOAI in db.KICHTHUOCs select LOAI;
            var list = loais.OrderBy(x => x.MAKICHTHUOC);
            return View(list.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(LOAI loai)
        {
            if (ModelState.IsValid)
            {
                db.LOAIs.Add(loai);
                db.SaveChanges();
            }
            return RedirectToAction("Index", "Loai");
        }
    }
}

WebPKthucung/Views/KichThuoc/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="create_admin">
    <h1 class="Title_Admin_create_form">Thêm màu sắc</h1>
    <p class="Notification_create_form">Vui lòng điền thông tin bên dưới</p>
    @using (Html.BeginForm("Create", "Loai", FormMethod.Post, new { @enctype = "multipart/form-data", @id = "form-3", @class = "create_admin_form" }))
    {
        @Html.AntiForgeryToken()
        <div class="form_field">
            <label for="" class="name_form_field">Sản phẩm : </label>
            <input type="text" class="textfile"  name="MASP">
            <span class="error_message"></span>
        </div>
        <div class="form_field">
            <label for="" class="name_form_field">Kích thức : </label>
            <input type="text" class="textfile" id="mausac" name="TENLOAI">
            <span class="error_message"></span>
        </div>
        <div class="button">
            <input type="button" value="Thêm" class="button_add_admin delete_display_alert" />
            <a href="@Url.Action("Index","KichThuoc")"><input type="button" value="Quay lại" class="button_add_admin" /></a>
        </div>
        <div class="alert_delete">
            <div class="notification">
                <h1 class="notification_title">Đã thêm màu sắc!</h1>
                <a href="@Url.Action("Index","KichThuoc")"><input type="submit" value="Ok" class="alert_delete_btn delete_conform" /></a>
            </div>
        </div>
    }
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Mong muốn của chúng ta
        Validator({
            form: '#form-3',
            formGroupSelector: '.form_field',
            errorSelector: '.error_message',
            rules: [
                Validator.isRequired('#mausac', 'Vui lòng nhập tên màu sắc!'),
            ],
            onSubmit: function (data) {
                // Call API
                //console.log(data);
            }
        });
    });
    const load = document.querySelector.bind(document);
    const alert_delete_btn = load(".delete_display_alert");
    const alert_delete_conform_btn = load(".delete_conform");
    const alert_delete = load(".alert_delete");
    alert_delete_btn.onclick = () => {
        alert_delete.style.display = "block";
    };
</script>

WebPKthucung/Views/KichThuoc/Index.cshtml
@using PagedList.Mvc;
@model PagedList.PagedList<WebPKthucung.Models.KICHTHUOC>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="table_header">
    <div class="add_admin">
        <a href="@Url.Action("Create","KichThuoc")">
            <i class="fa-solid fa-user-plus"></i>
            <div class="add_title">
                Thêm loại
            </div>
        </a>
    </div>
</div>
<table class="table_dsadmin">
    <thead>
        <tr>
            <th style="width: 65px;">Mã loại</th>
            <th style="width: 120px;">Tên Loại</th>
            <th style="width: 80px;">Chức năng</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr style="height: 50px;">
                <td>
                    @Html.DisplayFor(modelItem => item.MASP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TENKICHTHUOC)
                </td>

                <td>
                    <a href="@Url.Action("Edit","KichThuoc", new { id = item.MAKICHTHUOC })"><i class="fa-solid fa-pen-to-square edit"></i></a>
                    <a href="@Url.Action("Delete","KichThuoc", new { id = item.MAKICHTHUOC })"> <i class="fa-solid fa-xmark remove"></i></a>
                </td>
            </tr>
        }


    </tbody>
</table>
<ul class="page">
    @if (Model.PageCount > 1)
    {
        for (int i = 1; i <= Model.PageCount; i++)
        {
            <li>
                <a href="@Url.Action("Index", new { page = i })" class="@((i == Model.PageNumber) ? "page_button page_button_active" : "page_button")">@i</a>
            </li>
        }
    }
</ul>